version: '3'
services:
  apache-php:
    build:
      context: .
      dockerfile: Dockerfile-geofusion
    volumes:
      - apache-php-data:/var/www/html
    ports:
      - "70:80"
    networks:
      - lizmap-net
    depends_on:
      - qgis-server

  qgis-server:
    build:
      context: .
      dockerfile: Dockerfile-geofusion
    volumes:
      - qgis-server-data:/var/www/qgis-server
    ports:
      - "8080:80"
    networks:
      - lizmap-net

  lizmap:
    build:
      context: .
      dockerfile: Dockerfile-lizmap # Specifica il tuo Dockerfile per lizmap
    volumes:
      - lizmap-data:/var/www/lizmap
    ports:
      - "81:80"
    networks:
      - lizmap-net

networks:
  lizmap-net:

volumes:
  apache-php-data:
  qgis-server-data:
  lizmap-data:
