version: '3'

services:
  geofusion:
    build:
      context: .
      dockerfile: Dockerfile-Geofusion
    ports:
      - "80:80"
    volumes:
      - ./apache2.conf:/etc/apache2/sites-available/000-default.conf
      - ./fcgid.conf:/etc/apache2/mods-available/fcgid.conf
    environment:
      LIZMAP_VERSION: 3.6.4
    restart: always
